name: Check Links

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.md'

permissions:
  contents: read

jobs:
  check-links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress '**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
