name: Spell Check

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          files: '**/*.md'
          inline: warning
          config: |
            {
              "language": "en",
              "words": [
                "Windsurf",
                "markdownlint",
                "cspell",
                "lychee"
              ]
            }
